### ISSUE TITLE
Fix bitters error

### ISSUE THREAD

**Issue by khusnetdinov** [khusnetdinov/kazan#3]
/Users/khusnetdinov/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ffce14abd34 bitters-1.4.0> (NoMethodError)
	from /Users/khusnetdinov/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/khusnetdinov/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/gems/bitters-1.4.0/lib/bitters.rb:1:in `<top (required)>'
	from /Users/khusnetdinov/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/khusnetdinov/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/gems/bitters-1.4.0/bin/bitters:3:in `<top (required)>'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/bin/bitters:23:in `load'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/bin/bitters:23:in `<main>'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/khusnetdinov/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by khusnetdinov** [comment]
https://github.com/khusnetdinov/kazan/commit/49a44b3a46d3f8c2b6e086b9e5327c0de358c2dd
